import iplayerLogo from '../productLogos/iplayer.svg';
import soundsLogo from '../productLogos/sounds.svg';
import newsLogo from '../productLogos/news.svg';
import bitesizeLogo from '../productLogos/bitesize.svg';

// eslint-disable-next-line import/prefer-default-export
export const decadesContent = [
  {
    title: 'DECADES... The Dinosaurs',
    subTitle: 'BBC iPlayer',
    bodyText: 'The Dinosaurs are a group of ancient, non-human dinosaurs that lived in the late Jurassic period of the Cretaceous period. They were the first group of animals to exist in the world.',
    date: '1st Jan 1950',
    icon: iplayerLogo,
    iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
    contentStyle: { background: '#eeeeee', color: '#000' },
    contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  },
  {
    title: 'DECADES... England Win the World Cup',
    subTitle: 'BBC Sounds',
    bodyText: 'England won the World Cup in 1966, which was the first and only World Cup victory of their history.',
    date: '1st Jan 1966',
    icon: soundsLogo,
    iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
    contentStyle: { background: '#eeeeee', color: '#000' },
    contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  },
  {
    title: 'DECADES... The Dinosaurs',
    subTitle: 'BBC News',
    bodyText: 'The Dinosaurs are a group of ancient, non-human dinosaurs that lived in the late Jurassic period of the Cretaceous period. They were the first group of animals to exist in the world.',
    date: '1st Jan 1950',
    icon: newsLogo,
    iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
    contentStyle: { background: '#eeeeee', color: '#000' },
    contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  },
  {
    title: 'DECADES... England Win the World Cup',
    subTitle: 'BBC Bitesize',
    bodyText: 'England won the World Cup in 1966, which was the first and only World Cup victory of their history.',
    date: '1st Jan 1966',
    icon: bitesizeLogo,
    iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
    contentStyle: { background: '#eeeeee', color: '#000' },
    contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  },
  {
    title: 'DECADES... The Dinosaurs',
    subTitle: 'BBC iPlayer',
    bodyText: 'The Dinosaurs are a group of ancient, non-human dinosaurs that lived in the late Jurassic period of the Cretaceous period. They were the first group of animals to exist in the world.',
    date: '1st Jan 1950',
    icon: iplayerLogo,
    iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
    contentStyle: { background: '#eeeeee', color: '#000' },
    contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  },
  {
    title: 'DECADES... England Win the World Cup',
    subTitle: 'BBC Sounds',
    bodyText: 'England won the World Cup in 1966, which was the first and only World Cup victory of their history.',
    date: '1st Jan 1966',
    icon: soundsLogo,
    iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
    contentStyle: { background: '#eeeeee', color: '#000' },
    contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  },
  {
    title: 'DECADES... The Dinosaurs',
    subTitle: 'BBC News',
    bodyText: 'The Dinosaurs are a group of ancient, non-human dinosaurs that lived in the late Jurassic period of the Cretaceous period. They were the first group of animals to exist in the world.',
    date: '1st Jan 1950',
    icon: newsLogo,
    iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
    contentStyle: { background: '#eeeeee', color: '#000' },
    contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  },
  {
    title: 'DECADES... England Win the World Cup',
    subTitle: 'BBC Bitesize',
    bodyText: 'England won the World Cup in 1966, which was the first and only World Cup victory of their history.',
    date: '1st Jan 1966',
    icon: bitesizeLogo,
    iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
    contentStyle: { background: '#eeeeee', color: '#000' },
    contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  },
];

export const decadesContentObj = {
  '1950s': [
    {
      title: 'DECADES 1950s... The Dinosaurs',
      subTitle: 'BBC iPlayer',
      bodyText: 'The Dinosaurs are a group of ancient, non-human dinosaurs that lived in the late Jurassic period of the Cretaceous period. They were the first group of animals to exist in the world.',
      date: '1st Jan 1950',
      icon: iplayerLogo,
      iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
      contentStyle: { background: '#eeeeee', color: '#000' },
      contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
    },
    {
      title: 'DECADES 1950s... England Win the World Cup',
      subTitle: 'BBC Sounds',
      bodyText: 'England won the World Cup in 1966, which was the first and only World Cup victory of their history.',
      date: '1st Jan 1966',
      icon: soundsLogo,
      iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
      contentStyle: { background: '#eeeeee', color: '#000' },
      contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
    },
  ],
  '1960s': [
    {
      title: 'DECADES 1960s... The Dinosaurs',
      subTitle: 'BBC iPlayer',
      bodyText: 'The Dinosaurs are a group of ancient, non-human dinosaurs that lived in the late Jurassic period of the Cretaceous period. They were the first group of animals to exist in the world.',
      date: '1st Jan 1950',
      icon: iplayerLogo,
      iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
      contentStyle: { background: '#eeeeee', color: '#000' },
      contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
    },
    {
      title: 'DECADES 1960s... England Win the World Cup',
      subTitle: 'BBC Sounds',
      bodyText: 'England won the World Cup in 1966, which was the first and only World Cup victory of their history.',
      date: '1st Jan 1966',
      icon: soundsLogo,
      iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
      contentStyle: { background: '#eeeeee', color: '#000' },
      contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
    },
  ],
  '1970s': [
    {
      title: 'DECADES 1970s... The Dinosaurs',
      subTitle: 'BBC iPlayer',
      bodyText: 'The Dinosaurs are a group of ancient, non-human dinosaurs that lived in the late Jurassic period of the Cretaceous period. They were the first group of animals to exist in the world.',
      date: '1st Jan 1950',
      icon: iplayerLogo,
      iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
      contentStyle: { background: '#eeeeee', color: '#000' },
      contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
    },
    {
      title: 'DECADES 1970s... England Win the World Cup',
      subTitle: 'BBC Sounds',
      bodyText: 'England won the World Cup in 1966, which was the first and only World Cup victory of their history.',
      date: '1st Jan 1966',
      icon: soundsLogo,
      iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
      contentStyle: { background: '#eeeeee', color: '#000' },
      contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
    },
  ],
};
