import iplayerLogo from '../productLogos/iplayer.svg';
import soundsLogo from '../productLogos/sounds.svg';
import newsLogo from '../productLogos/news.svg';
import bitesizeLogo from '../productLogos/bitesize.svg';

// eslint-disable-next-line import/prefer-default-export
export const erasContent = [
  {
    title: 'The Dinosaurs',
    eraData: 'dinosaursBreakdown',
    subTitle: '',
    bodyText: 'The Dinosaurs are a group of ancient, non-human dinosaurs that lived in the late Jurassic period of the Cretaceous period. They were the first group of animals to exist in the world.',
    date: '300 million BC - 50 million BC',
    icon: iplayerLogo,
    iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
    contentStyle: { background: '#eeeeee', color: '#000' },
    contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  },
  {
    title: 'Sixtys',
    eraData: 'sixtysBreakdown',
    subTitle: '',
    bodyText: 'The sixtys were a vibrant era!',
    date: '1960 - 1969',
    icon: soundsLogo,
    iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
    contentStyle: { background: '#eeeeee', color: '#000' },
    contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  }
  // ,
  // {
  //   title: 'ERAS... The Dinosaurs',
  //   subTitle: 'BBC News',
  //   bodyText: 'The Dinosaurs are a group of ancient, non-human dinosaurs that lived in the late Jurassic period of the Cretaceous period. They were the first group of animals to exist in the world.',
  //   date: '1st Jan 1950',
  //   icon: newsLogo,
  //   iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
  //   contentStyle: { background: '#eeeeee', color: '#000' },
  //   contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  // },
  // {
  //   title: 'ERAS... England Win the World Cup',
  //   subTitle: 'BBC Bitesize',
  //   bodyText: 'England won the World Cup in 1966, which was the first and only World Cup victory of their history.',
  //   date: '1st Jan 1966',
  //   icon: bitesizeLogo,
  //   iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
  //   contentStyle: { background: '#eeeeee', color: '#000' },
  //   contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  // },
  // {
  //   title: 'ERAS... The Dinosaurs',
  //   subTitle: 'BBC iPlayer',
  //   bodyText: 'The Dinosaurs are a group of ancient, non-human dinosaurs that lived in the late Jurassic period of the Cretaceous period. They were the first group of animals to exist in the world.',
  //   date: '1st Jan 1950',
  //   icon: iplayerLogo,
  //   iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
  //   contentStyle: { background: '#eeeeee', color: '#000' },
  //   contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  // },
  // {
  //   title: 'ERAS... England Win the World Cup',
  //   subTitle: 'BBC Sounds',
  //   bodyText: 'England won the World Cup in 1966, which was the first and only World Cup victory of their history.',
  //   date: '1st Jan 1966',
  //   icon: soundsLogo,
  //   iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
  //   contentStyle: { background: '#eeeeee', color: '#000' },
  //   contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  // },
  // {
  //   title: 'ERAS... The Dinosaurs',
  //   subTitle: 'BBC News',
  //   bodyText: 'The Dinosaurs are a group of ancient, non-human dinosaurs that lived in the late Jurassic period of the Cretaceous period. They were the first group of animals to exist in the world.',
  //   date: '1st Jan 1950',
  //   icon: newsLogo,
  //   iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
  //   contentStyle: { background: '#eeeeee', color: '#000' },
  //   contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  // },
  // {
  //   title: 'ERAS... England Win the World Cup',
  //   subTitle: 'BBC Bitesize',
  //   bodyText: 'England won the World Cup in 1966, which was the first and only World Cup victory of their history.',
  //   date: '1st Jan 1966',
  //   icon: bitesizeLogo,
  //   iconStyle: { background: 'rgb(0, 0, 0)', color: '#eee' },
  //   contentStyle: { background: '#eeeeee', color: '#000' },
  //   contentArrowStyle: { borderRight: '7px solid  #eeeeee' },
  // },
];
